export interface QuestionItem {
  id: number;
  letter: string;
  spanishSentence: string;
  blankWord: string;
  armenianTranslation: string;
  tenseName: string; // e.g., "pretérito perfecto"
  tenseArmenian: string; // e.g., "Վաղակատար ներկա"
  options: {
    key: 'A' | 'B' | 'C' | 'D';
    text: string;
  }[];
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
}

export const QUESTIONS: QuestionItem[] = [
  {
    id: 1,
    letter: 'A',
    spanishSentence: 'Hoy yo ___ dos cafés.',
    blankWord: 'he bebido',
    armenianTranslation: 'Այսօր ես երկու սուրճ եմ խմել։',
    tenseName: 'pretérito perfecto',
    tenseArmenian: 'Վաղակատար ներկա',
    options: [
      { key: 'A', text: 'bebía' },
      { key: 'B', text: 'bebí' },
      { key: 'C', text: 'he bebido' },
      { key: 'D', text: 'había bebido' },
    ],
    correctAnswer: 'C',
    explanation: '«Hoy» (այսօր) ցույց է տալիս դեռ չավարտված ժամանակահատված, ուստի օգտագործվում է Pretérito Perfecto (he bebido)։',
  },
  {
    id: 2,
    letter: 'B',
    spanishSentence: 'Ayer Carlos ___ al supermercado después del trabajo.',
    blankWord: 'fue',
    armenianTranslation: 'Երեկ Կառլոսը աշխատանքից հետո գնաց սուպերմարկետ։',
    tenseName: 'pretérito indefinido',
    tenseArmenian: 'Պարզ անցյալ (կետային / ավարտված)',
    options: [
      { key: 'A', text: 'ha ido' },
      { key: 'B', text: 'fue' },
      { key: 'C', text: 'iba' },
      { key: 'D', text: 'había ido' },
    ],
    correctAnswer: 'B',
    explanation: '«Ayer» (երեկ) անցյալում լիովին ավարտված գործողություն է, ուստի օգտագործվում է Pretérito Indefinido (fue)։',
  },
  {
    id: 3,
    letter: 'C',
    spanishSentence: 'Cuando era pequeño, Pedro ___ con sus amigos todos los días.',
    blankWord: 'jugaba',
    armenianTranslation: 'Երբ Պեդրոն փոքր էր, ամեն օր խաղում էր իր ընկերների հետ։',
    tenseName: 'pretérito imperfecto',
    tenseArmenian: 'Անկատար անցյալ (սովորություն)',
    options: [
      { key: 'A', text: 'jugó' },
      { key: 'B', text: 'ha jugado' },
      { key: 'C', text: 'había jugado' },
      { key: 'D', text: 'jugaba' },
    ],
    correctAnswer: 'D',
    explanation: '«Todos los días» (ամեն օր) և մանկության նկարագրությունը ցույց են տալիս անցյալում կրկնվող սովորություն՝ Pretérito Imperfecto (jugaba)։',
  },
  {
    id: 4,
    letter: 'D',
    spanishSentence: 'Cuando llegué a casa, mi madre ya ___ la cena.',
    blankWord: 'había preparado',
    armenianTranslation: 'Երբ ես հասա տուն, մայրիկս արդեն պատրաստել էր ընթրիքը։',
    tenseName: 'pretérito pluscuamperfecto',
    tenseArmenian: 'Նախաանցյալ (անցյալից առաջ)',
    options: [
      { key: 'A', text: 'preparó' },
      { key: 'B', text: 'preparaba' },
      { key: 'C', text: 'ha preparado' },
      { key: 'D', text: 'había preparado' },
    ],
    correctAnswer: 'D',
    explanation: '«Ya» (արդեն) ցույց է տալիս, որ գործողությունն ավարտվել էր մինչև մյուս անցյալ պահը (տուն հասնելը)՝ Pretérito Pluscuamperfecto (había preparado)։',
  },
  {
    id: 5,
    letter: 'E',
    spanishSentence: 'Esta semana nosotros ___ mucho trabajo.',
    blankWord: 'hemos tenido',
    armenianTranslation: 'Այս շաբաթ մենք շատ աշխատանք ենք ունեցել։',
    tenseName: 'pretérito perfecto',
    tenseArmenian: 'Վաղակատար ներկա',
    options: [
      { key: 'A', text: 'tuvimos' },
      { key: 'B', text: 'teníamos' },
      { key: 'C', text: 'hemos tenido' },
      { key: 'D', text: 'habíamos tenido' },
    ],
    correctAnswer: 'C',
    explanation: '«Esta semana» (այս շաբաթ) դեռ շարունակվող ժամանակահատված է, ուստի՝ Pretérito Perfecto (hemos tenido)։',
  },
  {
    id: 6,
    letter: 'F',
    spanishSentence: 'El sábado pasado Lucía ___ una película muy interesante.',
    blankWord: 'vio',
    armenianTranslation: 'Անցած շաբաթ օրը Լուսիան շատ հետաքրքիր ֆիլմ դիտեց։',
    tenseName: 'pretérito indefinido',
    tenseArmenian: 'Պարզ անցյալ',
    options: [
      { key: 'A', text: 'veía' },
      { key: 'B', text: 'ha visto' },
      { key: 'C', text: 'había visto' },
      { key: 'D', text: 'vio' },
    ],
    correctAnswer: 'D',
    explanation: '«El sábado pasado» (անցած շաբաթ օրը) ավարտված անցյալ ժամանակ է՝ Pretérito Indefinido (vio)։',
  },
  {
    id: 7,
    letter: 'G',
    spanishSentence: 'Antes, mi abuelo ___ al trabajo a pie.',
    blankWord: 'iba',
    armenianTranslation: 'Նախկինում պապիկս աշխատանքի ոտքով էր գնում։',
    tenseName: 'pretérito imperfecto',
    tenseArmenian: 'Անկատար անցյալ (սովորույթ)',
    options: [
      { key: 'A', text: 'fue' },
      { key: 'B', text: 'ha ido' },
      { key: 'C', text: 'iba' },
      { key: 'D', text: 'había ido' },
    ],
    correctAnswer: 'C',
    explanation: '«Antes» (առաջ/նախկինում) ցույց է տալիս անցյալի կանոնավոր սովորույթ՝ Pretérito Imperfecto (iba)։',
  },
  {
    id: 8,
    letter: 'H',
    spanishSentence: 'Cuando empezó la película, nosotros ya ___.',
    blankWord: 'habíamos llegado',
    armenianTranslation: 'Երբ ֆիլմը սկսվեց, մենք արդեն հասել էինք։',
    tenseName: 'pretérito pluscuamperfecto',
    tenseArmenian: 'Նախաանցյալ',
    options: [
      { key: 'A', text: 'llegamos' },
      { key: 'B', text: 'hemos llegado' },
      { key: 'C', text: 'llegábamos' },
      { key: 'D', text: 'habíamos llegado' },
    ],
    correctAnswer: 'D',
    explanation: 'Ժամանումը տեղի էր ունեցել նախքան ֆիլմի սկսվելը՝ Pretérito Pluscuamperfecto (habíamos llegado)։',
  },
  {
    id: 9,
    letter: 'I',
    spanishSentence: '¿___ alguna vez comida mexicana?',
    blankWord: '¿Has comido?',
    armenianTranslation: 'Երբևէ մեքսիկական ուտելիք կերե՞լ ես։',
    tenseName: 'pretérito perfecto',
    tenseArmenian: 'Վաղակատար ներկա (կյանքի փորձ)',
    options: [
      { key: 'A', text: '¿Comías?' },
      { key: 'B', text: '¿Comiste?' },
      { key: 'C', text: '¿Has comido?' },
      { key: 'D', text: '¿Habías comido?' },
    ],
    correctAnswer: 'C',
    explanation: '«Alguna vez» (երբևէ) ակնարկում է անձի կյանքի փորձը մինչ այժմ՝ Pretérito Perfecto (¿Has comido?)։',
  },
  {
    id: 10,
    letter: 'J',
    spanishSentence: 'El año pasado nosotros ___ a Madrid.',
    blankWord: 'viajamos',
    armenianTranslation: 'Անցած տարի մենք ճանապարհորդեցինք Մադրիդ։',
    tenseName: 'pretérito indefinido',
    tenseArmenian: 'Պարզ անցյալ',
    options: [
      { key: 'A', text: 'viajábamos' },
      { key: 'B', text: 'hemos viajado' },
      { key: 'C', text: 'viajamos' },
      { key: 'D', text: 'habíamos viajado' },
    ],
    correctAnswer: 'C',
    explanation: '«El año pasado» (անցած տարի) ավարտված ժամանակային միջակայք է՝ Pretérito Indefinido (viajamos)։',
  },
  {
    id: 11,
    letter: 'K',
    spanishSentence: 'Cuando vivía en el pueblo, siempre ___ temprano.',
    blankWord: 'me despertaba',
    armenianTranslation: 'Երբ գյուղում էի ապրում, միշտ շուտ էի արթնանում։',
    tenseName: 'pretérito imperfecto',
    tenseArmenian: 'Անկատար անցյալ',
    options: [
      { key: 'A', text: 'me desperté' },
      { key: 'B', text: 'me he despertado' },
      { key: 'C', text: 'me había despertado' },
      { key: 'D', text: 'me despertaba' },
    ],
    correctAnswer: 'D',
    explanation: '«Siempre» (միշտ) անցյալում տևական սովորույթ է՝ Pretérito Imperfecto (me despertaba)։',
  },
  {
    id: 12,
    letter: 'L',
    spanishSentence: 'Ana no tenía hambre porque ya ___.',
    blankWord: 'había comido',
    armenianTranslation: 'Անան քաղցած չէր, որովհետև արդեն կերել էր։',
    tenseName: 'pretérito pluscuamperfecto',
    tenseArmenian: 'Նախաանցյալ',
    options: [
      { key: 'A', text: 'comió' },
      { key: 'B', text: 'comía' },
      { key: 'C', text: 'ha comido' },
      { key: 'D', text: 'había comido' },
    ],
    correctAnswer: 'D',
    explanation: 'Ուտելու գործողությունը նախորդել էր քաղցած չլինելուն՝ Pretérito Pluscuamperfecto (había comido)։',
  },
  {
    id: 13,
    letter: 'M',
    spanishSentence: 'Hoy mis amigos me ___ tres veces.',
    blankWord: 'han llamado',
    armenianTranslation: 'Այսօր ընկերներս ինձ երեք անգամ զանգել են։',
    tenseName: 'pretérito perfecto',
    tenseArmenian: 'Վաղակատար ներկա',
    options: [
      { key: 'A', text: 'llamaron' },
      { key: 'B', text: 'llamaban' },
      { key: 'C', text: 'han llamado' },
      { key: 'D', text: 'habían llamado' },
    ],
    correctAnswer: 'C',
    explanation: '«Hoy» (այսօր) դեռևս չավարտված օր է՝ Pretérito Perfecto (han llamado)։',
  },
  {
    id: 14,
    letter: 'N',
    spanishSentence: 'Anteayer Pablo ___ las llaves en el coche.',
    blankWord: 'dejó',
    armenianTranslation: 'Նախանցյալ օրը Պաբլոն բանալիները թողեց մեքենայի մեջ։',
    tenseName: 'pretérito indefinido',
    tenseArmenian: 'Պարզ անցյալ',
    options: [
      { key: 'A', text: 'dejaba' },
      { key: 'B', text: 'ha dejado' },
      { key: 'C', text: 'había dejado' },
      { key: 'D', text: 'dejó' },
    ],
    correctAnswer: 'D',
    explanation: '«Anteayer» (նախանցյալ օրը) հստակ ավարտված անցյալ է՝ Pretérito Indefinido (dejó)։',
  },
  {
    id: 15,
    letter: 'Ñ',
    spanishSentence: 'De niña, Lucía ___ mucho con su hermana.',
    blankWord: 'hablaba',
    armenianTranslation: 'Մանկության տարիներին Լուսիան շատ էր խոսում իր քրոջ հետ։',
    tenseName: 'pretérito imperfecto',
    tenseArmenian: 'Անկատար անցյալ',
    options: [
      { key: 'A', text: 'habló' },
      { key: 'B', text: 'ha hablado' },
      { key: 'C', text: 'había hablado' },
      { key: 'D', text: 'hablaba' },
    ],
    correctAnswer: 'D',
    explanation: '«De niña» (մանկության տարիներին) մանկության շրջանի նկարագրություն և սովորություն է՝ Pretérito Imperfecto (hablaba)։',
  },
  {
    id: 16,
    letter: 'O',
    spanishSentence: 'Cuando el profesor preguntó, yo ya ___ la respuesta.',
    blankWord: 'había entendido',
    armenianTranslation: 'Երբ ուսուցիչը հարցրեց, ես արդեն հասկացել էի պատասխանը։',
    tenseName: 'pretérito pluscuamperfecto',
    tenseArmenian: 'Նախաանցյալ',
    options: [
      { key: 'A', text: 'entendí' },
      { key: 'B', text: 'entendía' },
      { key: 'C', text: 'he entendido' },
      { key: 'D', text: 'había entendido' },
    ],
    correctAnswer: 'D',
    explanation: 'Հասկանալը տեղի էր ունեցել նախքան ուսուցչի հարցնելը՝ Pretérito Pluscuamperfecto (había entendido)։',
  },
  {
    id: 17,
    letter: 'P',
    spanishSentence: 'Este mes Carlos ___ tres libros.',
    blankWord: 'ha leído',
    armenianTranslation: 'Այս ամիս Կառլոսը երեք գիրք է կարդացել։',
    tenseName: 'pretérito perfecto',
    tenseArmenian: 'Վաղակատար ներկա',
    options: [
      { key: 'A', text: 'leyó' },
      { key: 'B', text: 'leía' },
      { key: 'C', text: 'ha leído' },
      { key: 'D', text: 'había leído' },
    ],
    correctAnswer: 'C',
    explanation: '«Este mes» (այս ամիս) ընթացիկ ամիսն է, որը դեռ չի ավարտվել՝ Pretérito Perfecto (ha leído)։',
  },
  {
    id: 18,
    letter: 'Q',
    spanishSentence: 'Anoche nosotros ___ muy tarde.',
    blankWord: 'dormimos',
    armenianTranslation: 'Անցած գիշեր մենք շատ ուշ քնեցինք։',
    tenseName: 'pretérito indefinido',
    tenseArmenian: 'Պարզ անցյալ',
    options: [
      { key: 'A', text: 'dormíamos' },
      { key: 'B', text: 'hemos dormido' },
      { key: 'C', text: 'habíamos dormido' },
      { key: 'D', text: 'dormimos' },
    ],
    correctAnswer: 'D',
    explanation: '«Anoche» (անցած գիշեր) ավարտված անցյալ գործողություն է՝ Pretérito Indefinido (dormimos)։',
  },
  {
    id: 19,
    letter: 'R',
    spanishSentence: 'Mientras mi madre cocinaba, yo ___ la mesa.',
    blankWord: 'preparaba',
    armenianTranslation: 'Մինչ մայրիկս պատրաստում էր ուտելիքը, ես սեղանն էի գցում։',
    tenseName: 'pretérito imperfecto',
    tenseArmenian: 'Անկատար անցյալ (զուգահեռ գործընթաց)',
    options: [
      { key: 'A', text: 'preparé' },
      { key: 'B', text: 'he preparado' },
      { key: 'C', text: 'preparaba' },
      { key: 'D', text: 'había preparado' },
    ],
    correctAnswer: 'C',
    explanation: '«Mientras» (մինչդեռ/քանի դեռ) նկարագրում է միաժամանակ տեղի ունեցող երկու անցյալ գործընթաց՝ Pretérito Imperfecto (preparaba)։',
  },
  {
    id: 20,
    letter: 'S',
    spanishSentence: 'Cuando fui a llamar a José, él ya ___.',
    blankWord: 'había salido',
    armenianTranslation: 'Երբ գնացի Խոսեին զանգելու, նա արդեն դուրս էր եկել։',
    tenseName: 'pretérito pluscuamperfecto',
    tenseArmenian: 'Նախաանցյալ',
    options: [
      { key: 'A', text: 'salió' },
      { key: 'B', text: 'salía' },
      { key: 'C', text: 'ha salido' },
      { key: 'D', text: 'había salido' },
    ],
    correctAnswer: 'D',
    explanation: 'Նա դուրս էր եկել նախքան զանգելու պահը՝ Pretérito Pluscuamperfecto (había salido)։',
  },
  {
    id: 21,
    letter: 'T',
    spanishSentence: 'Esta mañana ___ con mi profesor.',
    blankWord: 'he hablado',
    armenianTranslation: 'Այս առավոտ ես խոսել եմ իմ ուսուցչի հետ։',
    tenseName: 'pretérito perfecto',
    tenseArmenian: 'Վաղակատար ներկա',
    options: [
      { key: 'A', text: 'hablaba' },
      { key: 'B', text: 'hablé' },
      { key: 'C', text: 'había hablado' },
      { key: 'D', text: 'he hablado' },
    ],
    correctAnswer: 'D',
    explanation: '«Esta mañana» (այս առավոտ) այսօրվա շրջանակում է՝ Pretérito Perfecto (he hablado)։',
  },
  {
    id: 22,
    letter: 'U',
    spanishSentence: 'En 2024 mi familia ___ una casa nueva.',
    blankWord: 'compró',
    armenianTranslation: '2024 թվականին իմ ընտանիքը նոր տուն գնեց։',
    tenseName: 'pretérito indefinido',
    tenseArmenian: 'Պարզ անցյալ',
    options: [
      { key: 'A', text: 'compraba' },
      { key: 'B', text: 'ha comprado' },
      { key: 'C', text: 'compró' },
      { key: 'D', text: 'había comprado' },
    ],
    correctAnswer: 'C',
    explanation: '«En 2024» անցյալում ավարտված տարեթիվ է՝ Pretérito Indefinido (compró)։',
  },
  {
    id: 23,
    letter: 'V',
    spanishSentence: 'Cuando éramos estudiantes, ___ mucho tiempo juntos.',
    blankWord: 'pasábamos',
    armenianTranslation: 'Երբ ուսանող էինք, շատ ժամանակ էինք անցկացնում միասին։',
    tenseName: 'pretérito imperfecto',
    tenseArmenian: 'Անկատար անցյալ',
    options: [
      { key: 'A', text: 'pasamos' },
      { key: 'B', text: 'hemos pasado' },
      { key: 'C', text: 'habíamos pasado' },
      { key: 'D', text: 'pasábamos' },
    ],
    correctAnswer: 'D',
    explanation: 'Ուսանողական տարիների տևական սովորություն՝ Pretérito Imperfecto (pasábamos)։',
  },
  {
    id: 24,
    letter: 'W',
    spanishSentence: 'No pude entrar porque ___ las llaves en casa.',
    blankWord: 'había dejado',
    armenianTranslation: 'Ես չկարողացա ներս մտնել, որովհետև բանալիները տանը էի թողել։',
    tenseName: 'pretérito pluscuamperfecto',
    tenseArmenian: 'Նախաանցյալ',
    options: [
      { key: 'A', text: 'dejé' },
      { key: 'B', text: 'dejaba' },
      { key: 'C', text: 'he dejado' },
      { key: 'D', text: 'había dejado' },
    ],
    correctAnswer: 'D',
    explanation: 'Բանալիները թողնելը նախորդել էր ներս մտնել չկարողանալուն՝ Pretérito Pluscuamperfecto (había dejado)։',
  },
  {
    id: 25,
    letter: 'X',
    spanishSentence: '¿Qué ___ hoy para desayunar?',
    blankWord: 'has comido',
    armenianTranslation: 'Այսօր ի՞նչ ես կերել նախաճաշին։',
    tenseName: 'pretérito perfecto',
    tenseArmenian: 'Վաղակատար ներկա',
    options: [
      { key: 'A', text: 'comías' },
      { key: 'B', text: 'comiste' },
      { key: 'C', text: 'habías comido' },
      { key: 'D', text: 'has comido' },
    ],
    correctAnswer: 'D',
    explanation: '«Hoy» (այսօր) օրվա մեջ կատարված գործողության հարցում՝ Pretérito Perfecto (has comido)։',
  },
  {
    id: 26,
    letter: 'Y',
    spanishSentence: 'Ayer a las ocho yo ___ la cena cuando llamó Pedro.',
    blankWord: 'preparaba',
    armenianTranslation: 'Երեկ ժամը ութին ես ընթրիք էի պատրաստում, երբ Պեդրոն զանգեց։',
    tenseName: 'pretérito imperfecto',
    tenseArmenian: 'Անկատար անցյալ (ընթացքի մեջ գտնվող)',
    options: [
      { key: 'A', text: 'preparé' },
      { key: 'B', text: 'he preparado' },
      { key: 'C', text: 'había preparado' },
      { key: 'D', text: 'preparaba' },
    ],
    correctAnswer: 'D',
    explanation: 'Երբ Պեդրոն զանգեց, ընթրիք պատրաստելը դեռ ընթացքի մեջ էր (ֆոնային գործողություն)՝ Pretérito Imperfecto (preparaba)։',
  },
  {
    id: 27,
    letter: 'Z',
    spanishSentence: 'Cuando llegamos al aeropuerto, el avión ya ___.',
    blankWord: 'había salido',
    armenianTranslation: 'Երբ մենք հասանք օդանավակայան, ինքնաթիռն արդեն մեկնել էր։',
    tenseName: 'pretérito pluscuamperfecto',
    tenseArmenian: 'Նախաանցյալ',
    options: [
      { key: 'A', text: 'salió' },
      { key: 'B', text: 'salía' },
      { key: 'C', text: 'ha salido' },
      { key: 'D', text: 'había salido' },
    ],
    correctAnswer: 'D',
    explanation: 'Ինքնաթիռի մեկնումն արդեն տեղի էր ունեցել նախքան ժամանումը՝ Pretérito Pluscuamperfecto (había salido)։',
  },
];
